# Which YOLOE checkpoint to use (choose one)
# Text/visual prompted: yoloe-11{s|m|l}-seg.pt
# Prompt-free (large-vocab, no prompts): yoloe-11{s|m|l}-seg-pf.pt
weights: yoloe-11l-seg.pt

# Runtime
device: cuda:0         # "cpu" if no GPU
imgsz: 960             # 640/960/1280; balance speed vs accuracy
conf: 0.25             # confidence threshold
iou: 0.50              # NMS IoU
prompt_mode: text      # "text" or "prompt_free"
source: 0              # 0=webcam; or path/to/video.mp4
tcp_host: 127.0.0.1
tcp_port: 5555
send_masks: false      # true if you want instance masks later
